apiVersion: v1
kind: Service
metadata:
  name: hellok8s-service
spec:
  ports:
  - port: 8080
    targetPort: hellok8s-port
    nodePort: 31200
    protocol: TCP
  selector:
    app: hellok8s
  type: LoadBalancer